name: ensign
description: A flag Flutter package. Use for showing flags. All flags came from https://www.un.org/en/member-states/index.html . 
version: 5.0.4
homepage: https://github.com/ductung-bfast/flag_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/flag/
